### ISSUE TITLE
Channel Switch Announcement  in beacon frames?

### ISSUE THREAD

**Issue by mirasarkis** [kismetwireless/lorcon#1]
Hello,
I am currently using Lorcon to continuously send beacons in the network. 
I cannot figure how to extend the beacon frames to add "channel state announcement" to notify the network about a change in AP channel?
Thank you in advance for your help,
Regards,
Mira

**Comment by kismetwireless** [comment]
It should just be an IE tag - if you're manually creating the beacon you'll need to allocate the space in your buffer and craft the IE tag on it, if you're using the packet assembly system in lorcon you should be able to add it via lcpf_beacon and lcpf_add_ie.  I don't know the format for the channel switch IE tags offhand but it should be in the standards.
