### ISSUE TITLE
python3 compatibility for lorcon bindings

### ISSUE THREAD

**Issue by anthraxx** [kismetwireless/lorcon#11]
The python bindings are not compatible to be used with python3, are there any plans to port the bindings? They are required by the aircrack-ng airdrop-ng python script as well

**Comment by blshkv** [comment]
e15cf43a

**Comment by anthraxx** [comment]
any chance to get a release for that? @dragorn

**Comment by anthraxx** [comment]
gentle bump @dragorn may we get a new git tag so I can release this for our distro? its currently a blocker.

**Comment by kismetwireless** [comment]
tagged 2020.06.06

(actually thought had tagged it a while ago)

**Comment by anthraxx** [comment]
@kismetwireless awesome, thanks a lot. very much appreciated :cat:
