### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by xieyaxiongfly** [kismetwireless/lorcon#5]
Hi there,

I met a problem when compiling and installing lorcon in OpenWRT, the error information is as follow:
"install: cannot change ownership of '/home/alex/openwrt/trunk/openwrt/build_dir/target-mips_34kc_musl-│drv_airjack.c      drv_rt73.h        LICENSE             madwifing_control.o
1.1.16/lorcon-2017git/ipkg-install/usr/share/man/man3/lorcon.3': Operation not permitted              │drv_airjack.h      drv_rtl.c         Lindent             Makefile
make[4]: *** [install] Error 1  "

Any idea what's the problem here?

Thanks in advance.

**Comment by xieyaxiongfly** [comment]
In the Makefile, it runs 
install -o root -m 644 lorcon.3 $(MAN)/man3/lorcon.3

Do I need to remove the -o root?

**Comment by kismetwireless** [comment]
That would fix it for now, yes; it's trying to install the man pages w/ proper ownership.  They're likely unneeded on openwrt entirely.
