### ISSUE TITLE
lorcon_multi_set_interface_error_handler

### ISSUE THREAD

**Issue by netstd** [kismetwireless/lorcon#7]
I checked two commits: 267d90149aa76fa27a36b68e905e25b2fb99702e and 664942d62322159910f54c315025913b801c87e5

After the following:
./configure --libdir=/usr/lib
make
make install
cd pylorcon2/
python setup.py build
python setup.py install

I tried the following:
![default](https://user-images.githubusercontent.com/22892924/33741526-c72f7316-dbb5-11e7-9ec7-09f342d2520d.png)

**Comment by kismetwireless** [comment]
I suspect you've got another version of lorcon installed somewhere which is higher in your library order; I can confirm that lorcon in git exports those symbols:

```dragorn@drd1812-25:~/src/lorcon2$ nm ./.libs/liborcon2.so | grep lorcon_multi_
000000000000e900 T lorcon_multi_add_interface
000000000000e850 T lorcon_multi_create
000000000000e960 T lorcon_multi_del_interface
000000000000e890 T lorcon_multi_free
000000000000e840 T lorcon_multi_get_error
000000000000e9d0 T lorcon_multi_get_interfaces
000000000000e9e0 T lorcon_multi_get_next_interface
000000000000e9f0 T lorcon_multi_interface_get_lorcon
000000000000ea00 T lorcon_multi_loop
000000000000ed30 T lorcon_multi_remove_interface_error_handler
000000000000ecd0 T lorcon_multi_set_interface_error_handler
```

Try a `locate liborcon2.so` and see if you've got a version hanging around in another path.

**Comment by netstd** [comment]
Thank you very much for your response! I understood the cause of the error. Now everything worked even with the wireless adapter: KEBETEME Mini 802.11ac USB WiFi Adapter RTL8811AU
